name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: windows-latest
    strategy:
      max-parallel: 1

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - uses: BSFishy/pip-action@v1
      with:
        requirements: application/requirements.txt
    - name: Build exe
      run: |
        pyinstaller application/main.spec --windowed --onefile
